apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../base
  - image-automation.yaml
patchesStrategicMerge:
  - image-patch.yaml
  - image-policy-patch.yaml
