apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: balsmn/nginx:1.14.2-int # {"$imagepolicy": "qa:nginx"}
