apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: nginx-int
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-example-int
  update:
    strategy: Setters
    path: int
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: FluxIntBot
        email: fluxintbot@swdc.bosch-cs.com
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'