---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-example-dev
  namespace: dev
spec:
  interval: 1m0s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-example-dev

