---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-example-int
  namespace: qa
spec:
  interval: 1m0s
  path: ./int
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-example-int

