apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-example-int
  namespace: qa
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-example-repo-secret
  url: https://github.com/balsmn/flux2-kustomize-example.git

