apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: ngnix
  type: ClusterIP